baseURL = "https://kyuubang.github.io/"
languageCode = "en-us"
title = ">_ rawnotes"
theme="archie"
copyright = "© Kyuubang"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="auto"
	useCDN=false
	subtitle = "Raw note for mostly coding snippet, configuration, and cheatsheet."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Kyuubang"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4